# TCL File Generated by Component Editor 12.1sp1
# Tue Jul 14 18:57:06 CST 2015
# DO NOT MODIFY


# 
# remote_update_avalon "remote_update_avalon" v1.0
# Yogurt 2015.07.14.18:57:06
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module remote_update_avalon
# 
set_module_property NAME remote_update_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_ip/interface
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME remote_update_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL remote_update_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file remote_update_avalon_interface.v VERILOG PATH remote_update_avalon_interface.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1

# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clock
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true

add_interface_port rst_n rst_n reset_n Input 1

# 
# connection point control
# 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock
set_interface_property control associatedReset rst_n
set_interface_property control bitsPerSymbol 8
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 1
set_interface_property control readLatency 0
set_interface_property control readWaitTime 0
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0
set_interface_property control ENABLED true

add_interface_port control av_address address Input 6
add_interface_port control av_waitrequest waitrequest Output 1
add_interface_port control av_write write Input 1
add_interface_port control av_writedata writedata Input 32
add_interface_port control av_read read Input 1
add_interface_port control av_readdata readdata Output 32
add_interface_port control av_readdatavalid readdatavalid Output 1
set_interface_assignment control embeddedsw.configuration.isFlash 0
set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0

# 
# connection point remote_update_interface
# 
add_interface remote_update_interface conduit end
set_interface_property remote_update_interface associatedClock clock
set_interface_property remote_update_interface associatedReset rst_n
set_interface_property remote_update_interface ENABLED true

add_interface_port remote_update_interface ru_read_param export Output 1
add_interface_port remote_update_interface ru_write_param export Output 1
add_interface_port remote_update_interface ru_param export Output 3
add_interface_port remote_update_interface ru_datain export Output 22
add_interface_port remote_update_interface ru_source export Output 2
add_interface_port remote_update_interface ru_reset export Output 1
add_interface_port remote_update_interface ru_busy export Input 1
add_interface_port remote_update_interface ru_dataout export Input 29

