# TCL File Generated by Component Editor 12.1sp1
# Wed Jan 06 16:59:05 CST 2016
# DO NOT MODIFY


# 
# gen_reset_n "gen_reset_n" v1.0
# Yogurt 2016.01.06.16:59:05
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module gen_reset_n
# 
set_module_property DESCRIPTION "Generate Reset Output"
set_module_property NAME gen_reset_n
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_ip/other
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME gen_reset_n
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gen_reset_n
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file gen_reset_n.v VERILOG PATH gen_reset_n.v


# 
# parameters
# 
add_parameter ctr_width INTEGER 20
set_parameter_property ctr_width DEFAULT_VALUE 20
set_parameter_property ctr_width DISPLAY_NAME ctr_width
set_parameter_property ctr_width TYPE INTEGER
set_parameter_property ctr_width UNITS None
set_parameter_property ctr_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true

add_interface_port clock tx_clk clk Input 1


# 
# connection point reset_in
# 
add_interface reset_in reset end
set_interface_property reset_in associatedClock clock
set_interface_property reset_in synchronousEdges DEASSERT
set_interface_property reset_in ENABLED true

add_interface_port reset_in reset_n_in reset_n Input 1


# 
# connection point reset_out
# 
add_interface reset_out reset start
set_interface_property reset_out associatedClock clock
set_interface_property reset_out associatedDirectReset ""
set_interface_property reset_out associatedResetSinks ""
set_interface_property reset_out synchronousEdges DEASSERT
set_interface_property reset_out ENABLED true

add_interface_port reset_out reset_n_out reset_n Output 1

