# TCL File Generated by Component Editor 15.0
# Mon Oct 19 09:47:27 CST 2015
# DO NOT MODIFY


# 
# vip_raw_bridge "vip_raw_bridge" v1.0
# Yogurt 2015.10.19.09:47:27
# Yogurt 2016.07.20.11:14:00
# 


source "../../lib/aup_ip_generator.tcl"


# 
# module vip_raw_bridge
# 
set_module_property DESCRIPTION "Convert VIP Video Data to Raw Format"
set_module_property NAME vip_raw_bridge
set_module_property VERSION 1.1
set_module_property GROUP my_ip/video
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME vip_raw_bridge
set_module_property DATASHEET_URL "[pwd]/doc/VIP-to-Raw Bridge IP Core.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate

# 
# parameters
# 
add_parameter data_bits INTEGER 8
set_parameter_property data_bits DISPLAY_NAME "Data Bits"
set_parameter_property data_bits GROUP "Video In Format"
set_parameter_property data_bits UNITS None
set_parameter_property data_bits DISPLAY_UNITS Bits
set_parameter_property data_bits AFFECTS_ELABORATION true
set_parameter_property data_bits AFFECTS_GENERATION true
set_parameter_property data_bits ALLOWED_RANGES 4:32
set_parameter_property data_bits VISIBLE true
set_parameter_property data_bits ENABLED true


add_parameter data_planes INTEGER 3
set_parameter_property data_planes DISPLAY_NAME "Data Planes"
set_parameter_property data_planes GROUP "Video In Format"
set_parameter_property data_planes UNITS None
set_parameter_property data_planes DISPLAY_UNITS Planes
set_parameter_property data_planes AFFECTS_ELABORATION true
set_parameter_property data_planes AFFECTS_GENERATION true
set_parameter_property data_planes ALLOWED_RANGES {1 2 3}
set_parameter_property data_planes VISIBLE true
set_parameter_property data_planes ENABLED true


add_parameter extract_inf boolean false
set_parameter_property extract_inf DiSPLAY_NAME "Runtime Control"
set_parameter_property extract_inf GROUP "Runtime Control"
set_parameter_property extract_inf UNITS None
set_parameter_property extract_inf AFFECTS_ELABORATION true
set_parameter_property extract_inf AFFECTS_GENERATION true
set_parameter_property extract_inf VISIBLE true
set_parameter_property extract_inf ENABLED true

add_parameter control_mode INTEGER 0
set_parameter_property control_mode DISPLAY_NAME "Control Mode"
set_parameter_property control_mode GROUP "Runtime Control"
set_parameter_property control_mode UNITS None
set_parameter_property control_mode AFFECTS_ELABORATION true
set_parameter_property control_mode AFFECTS_GENERATION true
set_parameter_property control_mode ALLOWED_RANGES {0:Avalon-MM 1:Export}
set_parameter_property control_mode VISIBLE true
set_parameter_property control_mode ENABLED false

# +-----------------------------------
# | Validation function
# | 
proc validate {} {
	set extract_inf			[ get_parameter_value "extract_inf"]

	if { $extract_inf } {
		set_parameter_property control_mode ENABLED true
	} else {
		set_parameter_property control_mode ENABLED false
	}

}
# | 
# +-----------------------------------

# +-----------------------------------
# | Elaboration function
# | 
proc elaborate {} {
	set data_bits				[ get_parameter_value "data_bits"]
	set data_planes				[ get_parameter_value "data_planes"]
	set data_width				[ expr ($data_bits * $data_planes) ]

	set extract_inf				[ get_parameter_value "extract_inf"]
	set control_mode			[ get_parameter_value "control_mode"]

	# 
	# connection point clock
	# 
	add_interface clock clock end
	set_interface_property clock ENABLED true

	add_interface_port clock clk clk Input 1

	# 
	# connection point reset
	# 
	add_interface reset reset end
	set_interface_property reset associatedClock clock
	set_interface_property reset synchronousEdges DEASSERT
	set_interface_property reset ENABLED true

	add_interface_port reset rst_n reset_n Input 1

	# 
	# connection point din
	# 
	add_interface din avalon_streaming end
	set_interface_property din associatedClock clock
	set_interface_property din associatedReset reset
	set_interface_property din dataBitsPerSymbol $data_bits
	set_interface_property din errorDescriptor ""
	set_interface_property din firstSymbolInHighOrderBits true
	set_interface_property din maxChannel 0
	set_interface_property din readyLatency 1
	set_interface_property din ENABLED true

	add_interface_port din din_data data Input $data_width
	add_interface_port din din_valid valid Input 1
	add_interface_port din din_ready ready Output 1
	add_interface_port din din_startofpacket startofpacket Input 1
	add_interface_port din din_endofpacket endofpacket Input 1

	# 
	# connection point dout
	# 
	add_interface dout avalon_streaming start
	set_interface_property dout associatedClock clock
	set_interface_property dout associatedReset reset
	set_interface_property dout dataBitsPerSymbol $data_bits
	set_interface_property dout errorDescriptor ""
	set_interface_property dout firstSymbolInHighOrderBits true
	set_interface_property dout maxChannel 0
	set_interface_property dout readyLatency 1
	set_interface_property dout ENABLED true

	add_interface_port dout dout_data data Output $data_width
	add_interface_port dout dout_valid valid Output 1
	add_interface_port dout dout_ready ready Input 1
	add_interface_port dout dout_startofpacket startofpacket Output 1
	add_interface_port dout dout_endofpacket endofpacket Output 1

	if { $extract_inf } {
		if { $control_mode } {
			# 
			# connection point image_format
			# 
			add_interface image_format conduit end
			set_interface_property image_format associatedClock clock
			set_interface_property image_format associatedReset reset
			set_interface_property image_format ENABLED true

			add_interface_port image_format im_width export Output 16
			add_interface_port image_format im_height export Output 16
			add_interface_port image_format im_interlaced export Output 4
		} else {
			# 
			# connection point av_clk
			# 
			add_interface av_clk clock end
			set_interface_property av_clk ENABLED true
			add_interface_port av_clk av_clk clk Input 1

			# 
			# connection point av_rst_n
			# 
			add_interface av_rst_n reset end
			set_interface_property av_rst_n associatedClock av_clk
			set_interface_property av_rst_n synchronousEdges DEASSERT
			set_interface_property av_rst_n ENABLED true

			add_interface_port av_rst_n av_rst_n reset_n Input 1

			# 
			# connection point av_control
			# 
			add_interface av_control avalon end
			set_interface_property av_control addressUnits WORDS
			set_interface_property av_control associatedClock av_clk
			set_interface_property av_control associatedReset av_rst_n
			set_interface_property av_control bitsPerSymbol 8
			set_interface_property av_control burstOnBurstBoundariesOnly false
			set_interface_property av_control burstcountUnits WORDS
			set_interface_property av_control explicitAddressSpan 0
			set_interface_property av_control holdTime 0
			set_interface_property av_control linewrapBursts false
			set_interface_property av_control maximumPendingReadTransactions 8
			set_interface_property av_control readLatency 0
			set_interface_property av_control readWaitTime 0
			set_interface_property av_control setupTime 0
			set_interface_property av_control timingUnits Cycles
			set_interface_property av_control writeWaitTime 0
			set_interface_property av_control ENABLED true

			add_interface_port av_control av_address address Input 3
			add_interface_port av_control av_write write Input 1
			add_interface_port av_control av_writedata writedata Input 32
			add_interface_port av_control av_read read Input 1
			add_interface_port av_control av_readdata readdata Output 32
			add_interface_port av_control av_readdatavalid readdatavalid Output 1
			add_interface_port av_control av_waitrequest waitrequest Output 1
			
			set_interface_assignment av_control embeddedsw.configuration.isFlash 0
			set_interface_assignment av_control embeddedsw.configuration.isMemoryDevice 0
			set_interface_assignment av_control embeddedsw.configuration.isNonVolatileStorage 0
			set_interface_assignment av_control embeddedsw.configuration.isPrintableDevice 0
		}
	}

}
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	set data_bits				[ get_parameter_value "data_bits"]
	set data_planes				[ get_parameter_value "data_planes"]
	set data_width				[ expr ($data_bits * $data_planes) ]

	set extract_inf				[ get_parameter_value "extract_inf"]
	set control_mode			[ get_parameter_value "control_mode"]

	set data_width_p			"DATA_WIDTH:$data_width"
	set data_bits_p				"COLOR_BITS:$data_bits"
	set data_planes_p			"COLOR_PLANES:$data_planes"

	if { $extract_inf } {
		if { $control_mode } {
			set avalon_if		"AVALON_MM:0"
			set export_if		"EXPORT:1"
		} else {
			set avalon_if		"AVALON_MM:1"
			set export_if		"EXPORT:0"			
		}
	} else {
		set avalon_if			"AVALON_MM:0"
		set export_if			"EXPORT:0"	
	}

	set params "$data_width_p;$data_bits_p;$data_planes_p"
	set sections "$avalon_if;$export_if"

	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]

	add_file "$dest_dir$dest_name.v" SYNTHESIS
	alt_up_generate "$dest_dir$dest_name.v" "hdl/vrbridge_top.v" "vrbridge_top" $dest_name $params $sections
}
# | 
# +-----------------------------------
