# TCL File Generated by Component Editor 15.0
# Fri Nov 20 17:04:35 CST 2015
# DO NOT MODIFY


# 
# gray_balance "gray_balance" v1.1
# Yogurt 2015.11.20.17:04:35
# Yogurt 2015.11.30.17:30:00
# 

source "../../lib/aup_ip_generator.tcl"

# 
# module gray_balance
# 
set_module_property DESCRIPTION "Balance Gray Step"
set_module_property NAME gray_balance
set_module_property VERSION 1.1
set_module_property GROUP my_ip/video
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME gray_balance
set_module_property DATASHEET_URL "[pwd]/doc/Gray Balance IP Core.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate

# 
# file sets
# 

add_file "hdl/GB_comp.v" SYNTHESIS
add_file "hdl/GB_data_delay.v" SYNTHESIS
add_file "hdl/GB_decode.v" SYNTHESIS
add_file "hdl/GB_div.v" SYNTHESIS
add_file "hdl/GB_dout_fifo.v" SYNTHESIS
add_file "hdl/GB_encode.v" SYNTHESIS
add_file "hdl/GB_Gray_RAM_MUX.v" SYNTHESIS
add_file "hdl/GB_RAM.v" SYNTHESIS
add_file "hdl/GB_read_fifo.v" SYNTHESIS
add_file "hdl/GB_stat.v" SYNTHESIS
add_file "hdl/GB_state.v" SYNTHESIS

# 
# parameters
# 
add_parameter device_family STRING "Cyclone V"
set_parameter_property device_family DISPLAY_NAME "Device Family"
set_parameter_property device_family GROUP "General Setting"
set_parameter_property device_family UNITS NONE
set_parameter_property device_family AFFECTS_ELABORATION false
set_parameter_property device_family AFFECTS_GENERATION true
set_parameter_property device_family ALLOWED_RANGES {"Cyclone III" "Cyclone III LS" "Cyclone IV E" "Cyclone IV GX" "Cyclone V"}
set_parameter_property device_family VISIBLE true
set_parameter_property device_family ENABLED true

add_parameter div_latency INTEGER 4
set_parameter_property div_latency DISPLAY_NAME "Divide Latency"
set_parameter_property div_latency GROUP "General Setting"
set_parameter_property div_latency UNITS NONE
set_parameter_property div_latency AFFECTS_ELABORATION false
set_parameter_property div_latency AFFECTS_GENERATION true
set_parameter_property div_latency ALLOWED_RANGES 1:32
set_parameter_property div_latency VISIBLE true
set_parameter_property div_latency ENABLED true

add_parameter run_control boolean false
set_parameter_property run_control DiSPLAY_NAME "Runtime Control"
set_parameter_property run_control GROUP "Interface"
set_parameter_property run_control UNITS None
set_parameter_property run_control AFFECTS_ELABORATION true
set_parameter_property run_control AFFECTS_GENERATION true
set_parameter_property run_control VISIBLE true
set_parameter_property run_control ENABLED true

add_parameter control_mode INTEGER 0
set_parameter_property control_mode DISPLAY_NAME "Control Mode"
set_parameter_property control_mode GROUP "Interface"
set_parameter_property control_mode UNITS None
set_parameter_property control_mode AFFECTS_ELABORATION true
set_parameter_property control_mode AFFECTS_GENERATION true
set_parameter_property control_mode ALLOWED_RANGES {0:Avalon-MM 1:Export}
set_parameter_property control_mode VISIBLE true
set_parameter_property control_mode ENABLED false

add_parameter din_width INTEGER 14
set_parameter_property din_width DISPLAY_NAME "Input Data"
set_parameter_property din_width GROUP "Video Format"
set_parameter_property din_width UNITS NONE
set_parameter_property din_width DISPLAY_UNITS Bits
set_parameter_property din_width AFFECTS_ELABORATION true
set_parameter_property din_width AFFECTS_GENERATION true
set_parameter_property din_width ALLOWED_RANGES 4:32
set_parameter_property din_width VISIBLE true
set_parameter_property din_width ENABLED true

add_parameter dout_width INTEGER 10
set_parameter_property dout_width DISPLAY_NAME "Output Data"
set_parameter_property dout_width GROUP "Video Format"
set_parameter_property dout_width UNITS NONE
set_parameter_property dout_width DISPLAY_UNITS Bits
set_parameter_property dout_width AFFECTS_ELABORATION true
set_parameter_property dout_width AFFECTS_GENERATION true
set_parameter_property dout_width ALLOWED_RANGES 4:32
set_parameter_property dout_width VISIBLE true
set_parameter_property dout_width ENABLED true

# +-----------------------------------
# | Validation function
# | 
proc validate {} {
	set run_control			[ get_parameter_value "run_control"]

	if { $run_control } {
		set_parameter_property control_mode ENABLED true
	} else {
		set_parameter_property control_mode ENABLED false
	}

}
# | 
# +-----------------------------------

proc elaborate {} {
	set run_control			[get_parameter_value "run_control"]
	set control_mode		[get_parameter_value "control_mode"]
	set din_width			[get_parameter_value "din_width"]
	set dout_width			[get_parameter_value "dout_width"]

	# 
	# connection point clock
	# 
	add_interface clock clock end
	set_interface_property clock ENABLED true

	add_interface_port clock clk clk Input 1	

	# 
	# connection point reset
	# 
	add_interface reset reset end
	set_interface_property reset associatedClock clock
	set_interface_property reset synchronousEdges DEASSERT
	set_interface_property reset ENABLED true

	add_interface_port reset rst_n reset_n Input 1

	if { $run_control } {
		if { $control_mode } {
			add_interface interface conduit end
			set_interface_property interface associatedClock clock
			set_interface_property interface associatedReset reset
			set_interface_property interface ENABLED true

			add_interface_port interface inf_ena export Input 1
			add_interface_port interface inf_stat export Output [ expr ($din_width + 1) ]
		} else {
			# 
			# connection point control
			# 
			add_interface control avalon end
			set_interface_property control addressUnits WORDS
			set_interface_property control associatedClock clock
			set_interface_property control associatedReset reset
			set_interface_property control bitsPerSymbol 8
			set_interface_property control burstOnBurstBoundariesOnly false
			set_interface_property control burstcountUnits WORDS
			set_interface_property control explicitAddressSpan 0
			set_interface_property control holdTime 0
			set_interface_property control linewrapBursts false
			set_interface_property control maximumPendingReadTransactions 0
			set_interface_property control readLatency 1
			set_interface_property control readWaitTime 0
			set_interface_property control setupTime 0
			set_interface_property control timingUnits Cycles
			set_interface_property control writeWaitTime 0
			set_interface_property control ENABLED true

			add_interface_port control av_address address Input 1
			add_interface_port control av_read read Input 1
			add_interface_port control av_write write Input 1
			add_interface_port control av_readdata readdata Output 32
			add_interface_port control av_writedata writedata Input 32
		}

	}

	# 
	# connection point din
	# 
	add_interface din avalon_streaming end
	set_interface_property din associatedClock clock
	set_interface_property din associatedReset reset
	set_interface_property din dataBitsPerSymbol $din_width
	set_interface_property din errorDescriptor ""
	set_interface_property din maxChannel 0
	set_interface_property din readyLatency 1
	set_interface_property din ENABLED true

	add_interface_port din din_data data Input $din_width
	add_interface_port din din_valid valid Input 1
	add_interface_port din din_ready ready Output 1
	add_interface_port din din_startofpacket startofpacket Input 1
	add_interface_port din din_endofpacket endofpacket Input 1

	# 
	# connection point dout
	# 
	add_interface dout avalon_streaming start
	set_interface_property dout associatedClock clock
	set_interface_property dout associatedReset reset
	set_interface_property dout dataBitsPerSymbol $dout_width
	set_interface_property dout errorDescriptor ""
	set_interface_property dout maxChannel 0
	set_interface_property dout readyLatency 1
	set_interface_property dout ENABLED true

	add_interface_port dout dout_data data Output $dout_width
	add_interface_port dout dout_valid valid Output 1
	add_interface_port dout dout_ready ready Input 1
	add_interface_port dout dout_startofpacket startofpacket Output 1
	add_interface_port dout dout_endofpacket endofpacket Output 1
}

proc generate {} {
	set device_family		[get_parameter_value "device_family"]
	set div_latency			[get_parameter_value "div_latency"]
	set run_control			[get_parameter_value "run_control"]
	set control_mode		[get_parameter_value "control_mode"]
	set din_width			[get_parameter_value "din_width"]
	set dout_width			[get_parameter_value "dout_width"]


	set device_family_p			"DEVICE_FAMILY:\"$device_family\""
	set din_width_p				"DIN_WIDTH:$din_width"
	set dout_width_p			"DOUT_WIDTH:$dout_width"
	set div_latency_p			"DIV_LATENCY:$div_latency"

	if { $run_control } {
		if { $control_mode } {
			set avalon_if "RUN_CONTROL:0"
			set export_if "EXPORT:1"
		} else {
			set avalon_if "RUN_CONTROL:1"
			set export_if "EXPORT:0"			
		}
	} else {
		set avalon_if "RUN_CONTROL:0"
		set export_if "EXPORT:0"
	}

	set params "$device_family_p;$din_width_p;$dout_width_p;$div_latency_p"
	set sections "$avalon_if;$export_if"

	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]

	add_file "$dest_dir$dest_name.v" SYNTHESIS
	alt_up_generate "$dest_dir$dest_name.v" "hdl/GB_top.v" "GB_top" $dest_name $params $sections
}
