# TCL File Generated by Component Editor 12.1sp1
# Wed Jun 24 18:25:43 CST 2015
# DO NOT MODIFY


# 
# pll_avalon_interface "pll_avalon_interface" v1.0
# Yogurt 2015.06.24.18:25:43
# Interface For PLL
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module pll_avalon_interface
# 
set_module_property DESCRIPTION "Interface For PLL"
set_module_property NAME pll_avalon_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_ip/interface
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME pll_avalon_interface
set_module_property DATASHEET_URL "[pwd]/doc/PLL Avalon Interface Core.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pll_avalon_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "hdl/pll_avalon_module.v" VERILOG PATH "hdl/pll_avalon_module.v"


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset rst_n reset_n Input 1

# 
# connection point avalon_interface
# 
add_interface avalon_interface avalon end
set_interface_property avalon_interface addressUnits WORDS
set_interface_property avalon_interface associatedClock clock
set_interface_property avalon_interface associatedReset reset
set_interface_property avalon_interface bitsPerSymbol 8
set_interface_property avalon_interface burstOnBurstBoundariesOnly false
set_interface_property avalon_interface burstcountUnits WORDS
set_interface_property avalon_interface explicitAddressSpan 0
set_interface_property avalon_interface holdTime 0
set_interface_property avalon_interface linewrapBursts false
set_interface_property avalon_interface maximumPendingReadTransactions 4
set_interface_property avalon_interface readLatency 0
set_interface_property avalon_interface readWaitTime 1
set_interface_property avalon_interface setupTime 0
set_interface_property avalon_interface timingUnits Cycles
set_interface_property avalon_interface writeWaitTime 0
set_interface_property avalon_interface ENABLED true

add_interface_port avalon_interface av_address address Input 2
add_interface_port avalon_interface av_read read Input 1
add_interface_port avalon_interface av_write write Input 1
add_interface_port avalon_interface av_readdata readdata Output 32
add_interface_port avalon_interface av_waitrequest waitrequest Output 1
add_interface_port avalon_interface av_readdatavalid readdatavalid Output 1
add_interface_port avalon_interface av_writedata writedata Input 32

set_interface_assignment avalon_interface embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_interface embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_interface embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_interface embeddedsw.configuration.isPrintableDevice 0

# 
# connection point pll_interface
# 
add_interface pll_interface conduit end
set_interface_property pll_interface associatedClock clock
set_interface_property pll_interface associatedReset reset
set_interface_property pll_interface ENABLED true

add_interface_port pll_interface pll_phasedone export Input 1
add_interface_port pll_interface pll_locked export Input 1
add_interface_port pll_interface pll_pfdena export Output 1
add_interface_port pll_interface pll_areset export Output 1
add_interface_port pll_interface pll_phasecounterselect export Output 3
add_interface_port pll_interface pll_phaseupdown export Output 1
add_interface_port pll_interface pll_phasestep export Output 1
