# TCL File Generated by Component Editor 12.1sp1
# Wed Jul 22 15:42:04 CST 2015
# DO NOT MODIFY


# 
# raw_vip_bridge "raw_vip_bridge" v1.4
# Yogurt 2015.07.22.15:42:04
# Yogurt 2015.09.01.10:29:00
# Yogurt 2015.09.08.10:59:00
# Yogurt 2015.10.19.17:09:00
# Yogurt 2016.09.04.20:04:00


source "../../lib/aup_ip_generator.tcl"

# 
# module raw_vip_bridge
# 
set_module_property DESCRIPTION "Convert Raw Video Data to VIP Format"
set_module_property NAME raw_vip_bridge
set_module_property VERSION 1.4
set_module_property GROUP my_ip/video
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME raw_vip_bridge
set_module_property DATASHEET_URL "[pwd]/doc/Raw-to-VIP Bridge IP Core.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate

# 
# file sets
# 
add_file "hdl/rvbridge_make_se.v" SYNTHESIS
add_file "hdl/rvbridge_read_fifo.v" SYNTHESIS
add_file "hdl/rvbridge_fifo_pixel_sc.v" SYNTHESIS
add_file "hdl/rvbridge_fifo_pixel_dc.v" SYNTHESIS
add_file "hdl/rvbridge_encode.v" SYNTHESIS

# 
# parameters
# 
add_parameter data_bits INTEGER 8
set_parameter_property data_bits DISPLAY_NAME "Data Bits"
set_parameter_property data_bits GROUP "Video In Format"
set_parameter_property data_bits UNITS None
set_parameter_property data_bits DISPLAY_UNITS Bits
set_parameter_property data_bits AFFECTS_ELABORATION true
set_parameter_property data_bits AFFECTS_GENERATION true
set_parameter_property data_bits ALLOWED_RANGES 4:32
set_parameter_property data_bits VISIBLE true
set_parameter_property data_bits ENABLED true

add_parameter data_planes INTEGER 1
set_parameter_property data_planes DISPLAY_NAME "Data Planes"
set_parameter_property data_planes GROUP "Video In Format"
set_parameter_property data_planes UNITS None
set_parameter_property data_planes DISPLAY_UNITS Planes
set_parameter_property data_planes AFFECTS_ELABORATION true
set_parameter_property data_planes AFFECTS_GENERATION true
set_parameter_property data_planes ALLOWED_RANGES {1 2 3}
set_parameter_property data_planes VISIBLE true
set_parameter_property data_planes ENABLED true

add_parameter data_mode INTEGER 1
set_parameter_property data_mode DISPLAY_NAME "Data Mode"
set_parameter_property data_mode GROUP "Video In Format"
set_parameter_property data_mode UNITS None
set_parameter_property data_mode AFFECTS_ELABORATION true
set_parameter_property data_mode AFFECTS_GENERATION true
set_parameter_property data_mode ALLOWED_RANGES {1:FS 2:PART_ST 3:RAW_ST}
set_parameter_property data_mode VISIBLE true
set_parameter_property data_mode ENABLED true

add_parameter same_clk boolean false
set_parameter_property same_clk DiSPLAY_NAME "Video In and Out Use Same Clock"
set_parameter_property same_clk GROUP "Video In Format"
set_parameter_property same_clk UNITS None
set_parameter_property same_clk AFFECTS_ELABORATION true
set_parameter_property same_clk AFFECTS_GENERATION true
set_parameter_property same_clk VISIBLE true
set_parameter_property same_clk ENABLED true


add_parameter fifo_depth INTEGER 4096
set_parameter_property fifo_depth DISPLAY_NAME "FIFO Depth"
set_parameter_property fifo_depth GROUP "FIFO Setting"
set_parameter_property fifo_depth UNITS None
set_parameter_property fifo_depth AFFECTS_ELABORATION true
set_parameter_property fifo_depth AFFECTS_GENERATION true
set_parameter_property fifo_depth ALLOWED_RANGES {256 512 1024 2048 4096 8192 16384 32768 65536 131072}
set_parameter_property fifo_depth VISIBLE true
set_parameter_property fifo_depth ENABLED true

add_parameter buffer_num INTEGER 1024
set_parameter_property buffer_num DISPLAY_NAME "FIFO Buffer Pixels"
set_parameter_property buffer_num GROUP "FIFO Setting"
set_parameter_property buffer_num UNITS None
set_parameter_property buffer_num AFFECTS_ELABORATION false
set_parameter_property buffer_num AFFECTS_GENERATION true
set_parameter_property buffer_num VISIBLE true
set_parameter_property buffer_num ENABLED true

add_parameter fifo_use boolean false
set_parameter_property fifo_use DiSPLAY_NAME "Export FIFO Usedw"
set_parameter_property fifo_use GROUP "FIFO Setting"
set_parameter_property fifo_use UNITS None
set_parameter_property fifo_use AFFECTS_ELABORATION true
set_parameter_property fifo_use AFFECTS_GENERATION true
set_parameter_property fifo_use VISIBLE true
set_parameter_property fifo_use ENABLED true


add_parameter video_width INTEGER 720
set_parameter_property video_width DISPLAY_NAME "Video Width"
set_parameter_property video_width GROUP "Video Out Format"
set_parameter_property video_width UNITS None
set_parameter_property video_width DISPLAY_UNITS Pixels
set_parameter_property video_width AFFECTS_ELABORATION false
set_parameter_property video_width AFFECTS_GENERATION true
set_parameter_property video_width VISIBLE true
set_parameter_property video_width ENABLED true

add_parameter video_height INTEGER 576
set_parameter_property video_height DISPLAY_NAME "Video Height"
set_parameter_property video_height GROUP "Video Out Format"
set_parameter_property video_height UNITS None
set_parameter_property video_height DISPLAY_UNITS Lines
set_parameter_property video_height AFFECTS_ELABORATION false
set_parameter_property video_height AFFECTS_GENERATION true
set_parameter_property video_height VISIBLE true
set_parameter_property video_height ENABLED true

add_parameter video_interlaced string "0010"
set_parameter_property video_interlaced DISPLAY_NAME "Video Interlaced"
set_parameter_property video_interlaced GROUP "Video Out Format"
set_parameter_property video_interlaced UNITS None
set_parameter_property video_interlaced AFFECTS_ELABORATION false
set_parameter_property video_interlaced AFFECTS_GENERATION true
set_parameter_property video_interlaced ALLOWED_RANGES {0010:Progressive 1010:F0 1110:F1}
set_parameter_property video_interlaced VISIBLE true
set_parameter_property video_interlaced ENABLED true


add_parameter runtime_control boolean false
set_parameter_property runtime_control DiSPLAY_NAME "Runtime Control"
set_parameter_property runtime_control GROUP "Runtime Control"
set_parameter_property runtime_control UNITS None
set_parameter_property runtime_control AFFECTS_ELABORATION true
set_parameter_property runtime_control AFFECTS_GENERATION true
set_parameter_property runtime_control VISIBLE true
set_parameter_property runtime_control ENABLED true

add_parameter control_mode INTEGER 0
set_parameter_property control_mode DISPLAY_NAME "Control Mode"
set_parameter_property control_mode GROUP "Runtime Control"
set_parameter_property control_mode UNITS None
set_parameter_property control_mode AFFECTS_ELABORATION true
set_parameter_property control_mode AFFECTS_GENERATION true
set_parameter_property control_mode ALLOWED_RANGES {0:Avalon-MM 1:Export}
set_parameter_property control_mode VISIBLE true
set_parameter_property control_mode ENABLED false

# +-----------------------------------
# | Validation function
# | 
proc validate {} {
	set data_mode				[ get_parameter_value "data_mode" ]
	set runtime_control			[ get_parameter_value "runtime_control"]
	set fifo_depth				[ get_parameter_value "fifo_depth"]
	set buffer_num				[ get_parameter_value "buffer_num"]

	if { $data_mode == 3 } {
		set_parameter_property same_clk ENABLED false
		set_parameter_property fifo_depth ENABLED false
		set_parameter_property fifo_use ENABLED false
	} else {
		set_parameter_property same_clk ENABLED true
		set_parameter_property fifo_depth ENABLED true
		set_parameter_property fifo_use ENABLED true	
	}

	if { $runtime_control } {
		set_parameter_property control_mode ENABLED true
	} else {
		set_parameter_property control_mode ENABLED false
	}

	if { $fifo_depth <= $buffer_num} {
		send_message error "The Buffer Pixles Must Not Bigger Than FIFO Depth."
	}

}
# | 
# +-----------------------------------

# +-----------------------------------
# | Elaboration function
# | 
proc elaborate {} {
	set data_bits				[ get_parameter_value "data_bits"]
	set data_planes				[ get_parameter_value "data_planes"]
	set data_mode				[ get_parameter_value "data_mode" ]
	set same_clk				[ get_parameter_value "same_clk"]
	set fifo_depth				[ get_parameter_value "fifo_depth"]
	set fifo_use				[ get_parameter_value "fifo_use"]
	set runtime_control			[ get_parameter_value "runtime_control"]
	set control_mode			[ get_parameter_value "control_mode"]

	set data_width				[ expr ($data_bits * $data_planes) ]

	if { $same_clk=="false" && $data_mode!=3} {
		add_interface raw_clk clock end
		set_interface_property raw_clk ENABLED true
		add_interface_port raw_clk raw_clk clk Input 1	

		add_interface raw_rst_n reset end
		set_interface_property raw_rst_n associatedClock raw_clk
		set_interface_property raw_rst_n synchronousEdges DEASSERT
		set_interface_property raw_rst_n ENABLED true
		add_interface_port raw_rst_n raw_rst_n reset_n Input 1
	}

	# 
	# connection point clk
	# 
	add_interface vst_clk clock end
	set_interface_property vst_clk ENABLED true

	add_interface_port vst_clk vst_clk clk Input 1

	# 
	# connection point rst_n
	# 
	add_interface vst_rst_n reset end
	set_interface_property vst_rst_n associatedClock vst_clk
	set_interface_property vst_rst_n synchronousEdges DEASSERT
	set_interface_property vst_rst_n ENABLED true

	add_interface_port vst_rst_n vst_rst_n reset_n Input 1

	switch $data_mode {
		1 {
			if { $same_clk } {
				add_interface raw_video avalon_streaming end 
				set_interface_property raw_video associatedClock vst_clk
				set_interface_property raw_video associatedReset vst_rst_n
				set_interface_property raw_video dataBitsPerSymbol $data_bits
				set_interface_property raw_video errorDescriptor ""
				set_interface_property raw_video maxChannel 0
				set_interface_property raw_video readyLatency 1
				set_interface_property raw_video symbolsPerBeat $data_planes	
			} else {
				add_interface raw_video avalon_streaming end 
				set_interface_property raw_video associatedClock raw_clk
				set_interface_property raw_video associatedReset raw_rst_n
				set_interface_property raw_video dataBitsPerSymbol $data_bits
				set_interface_property raw_video errorDescriptor ""
				set_interface_property raw_video maxChannel 0
				set_interface_property raw_video readyLatency 1
				set_interface_property raw_video symbolsPerBeat $data_planes
			}
			add_interface_port raw_video raw_data data Input $data_width
			add_interface_port raw_video raw_fs valid Input 1		
		}
		2 {
			if { $same_clk } {
				add_interface raw_video avalon_streaming end 
				set_interface_property raw_video associatedClock vst_clk
				set_interface_property raw_video associatedReset vst_rst_n
				set_interface_property raw_video dataBitsPerSymbol $data_bits
				set_interface_property raw_video errorDescriptor ""
				set_interface_property raw_video maxChannel 0
				set_interface_property raw_video readyLatency 1
				set_interface_property raw_video symbolsPerBeat $data_planes	
			} else {
				add_interface raw_video avalon_streaming end 
				set_interface_property raw_video associatedClock raw_clk
				set_interface_property raw_video associatedReset raw_rst_n
				set_interface_property raw_video dataBitsPerSymbol $data_bits
				set_interface_property raw_video errorDescriptor ""
				set_interface_property raw_video maxChannel 0
				set_interface_property raw_video readyLatency 1
				set_interface_property raw_video symbolsPerBeat $data_planes
			}
			add_interface_port raw_video raw_data data Input $data_width
			add_interface_port raw_video raw_valid valid Input 1
			add_interface_port raw_video raw_startofpacket startofpacket Input 1
			add_interface_port raw_video raw_endofpacket endofpacket Input 1
		}
		3 {
			add_interface raw_video avalon_streaming end 
			set_interface_property raw_video associatedClock vst_clk
			set_interface_property raw_video associatedReset vst_rst_n
			set_interface_property raw_video dataBitsPerSymbol $data_bits
			set_interface_property raw_video errorDescriptor ""
			set_interface_property raw_video maxChannel 0
			set_interface_property raw_video readyLatency 1
			set_interface_property raw_video symbolsPerBeat $data_planes
			
			add_interface_port raw_video raw_data data Input $data_width
			add_interface_port raw_video raw_valid valid Input 1
			add_interface_port raw_video raw_startofpacket startofpacket Input 1
			add_interface_port raw_video raw_endofpacket endofpacket Input 1
			add_interface_port raw_video raw_ready ready Output 1
		}
	}

	# 
	# connection point dout
	# 
	add_interface dout avalon_streaming start
	set_interface_property dout associatedClock vst_clk
	set_interface_property dout associatedReset vst_rst_n
	set_interface_property dout dataBitsPerSymbol $data_bits
	set_interface_property dout errorDescriptor ""
	set_interface_property dout maxChannel 0
	set_interface_property dout readyLatency 1
	set_interface_property dout symbolsPerBeat $data_planes

	add_interface_port dout dout_data data Output $data_width
	add_interface_port dout dout_valid valid Output 1
	add_interface_port dout dout_ready ready Input 1
	add_interface_port dout dout_startofpacket startofpacket Output 1
	add_interface_port dout dout_endofpacket endofpacket Output 1

	if { $runtime_control } {
		if { $control_mode } {
			add_interface image_data conduit end
			set_interface_property image_data associatedClock vst_clk
			set_interface_property image_data associatedReset vst_rst_n
			set_interface_property image_data ENABLED true

			add_interface_port image_data im_width export Input 16
			add_interface_port image_data im_height export Input 16
			add_interface_port image_data im_interlaced export Input 4
		} else {
			# 
			# connection point av_clk
			# 
			add_interface av_clk clock end
			set_interface_property av_clk ENABLED true
			add_interface_port av_clk av_clk clk Input 1

			# 
			# connection point av_rst_n
			# 
			add_interface av_rst_n reset end
			set_interface_property av_rst_n associatedClock av_clk
			set_interface_property av_rst_n synchronousEdges DEASSERT
			set_interface_property av_rst_n ENABLED true

			add_interface_port av_rst_n av_rst_n reset_n Input 1

			# 
			# connection point av_control
			# 
			add_interface av_control avalon end
			set_interface_property av_control addressUnits WORDS
			set_interface_property av_control associatedClock av_clk
			set_interface_property av_control associatedReset av_rst_n
			set_interface_property av_control bitsPerSymbol 8
			set_interface_property av_control burstOnBurstBoundariesOnly false
			set_interface_property av_control burstcountUnits WORDS
			set_interface_property av_control explicitAddressSpan 0
			set_interface_property av_control holdTime 0
			set_interface_property av_control linewrapBursts false
			set_interface_property av_control maximumPendingReadTransactions 8
			set_interface_property av_control readLatency 0
			set_interface_property av_control readWaitTime 0
			set_interface_property av_control setupTime 0
			set_interface_property av_control timingUnits Cycles
			set_interface_property av_control writeWaitTime 0
			set_interface_property av_control ENABLED true

			add_interface_port av_control av_address address Input 3
			add_interface_port av_control av_write write Input 1
			add_interface_port av_control av_writedata writedata Input 32
			add_interface_port av_control av_read read Input 1
			add_interface_port av_control av_readdata readdata Output 32
			add_interface_port av_control av_readdatavalid readdatavalid Output 1
			add_interface_port av_control av_waitrequest waitrequest Output 1
			
			set_interface_assignment av_control embeddedsw.configuration.isFlash 0
			set_interface_assignment av_control embeddedsw.configuration.isMemoryDevice 0
			set_interface_assignment av_control embeddedsw.configuration.isNonVolatileStorage 0
			set_interface_assignment av_control embeddedsw.configuration.isPrintableDevice 0

			# 
			# connection point irq
			# 
			add_interface irq interrupt end
			set_interface_property irq associatedAddressablePoint av_control
			set_interface_property irq associatedClock av_clk
			set_interface_property irq associatedReset av_rst_n
			set_interface_property irq ENABLED true

			add_interface_port irq av_irq irq Output 1
		}
	}

	if { ($fifo_use) && ($data_mode!=3) } {
		set fifo_use_width [ format "%.0f" [ expr ceil (log($fifo_depth) / (log (2))) ]]

		# 
		# connection point fifo_max_usedw
		# 
		add_interface fifo_usedw conduit end
		set_interface_property fifo_usedw associatedClock vst_clk
		set_interface_property fifo_usedw associatedReset vst_rst_n
		set_interface_property fifo_usedw ENABLED true

		add_interface_port fifo_usedw fifo_usedw export Output $fifo_use_width
	}
}
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	set data_bits				[ get_parameter_value "data_bits"]
	set data_planes				[ get_parameter_value "data_planes"]
	set data_mode				[ get_parameter_value "data_mode" ]
	set same_clk				[ get_parameter_value "same_clk"]
	set fifo_depth				[ get_parameter_value "fifo_depth"]
	set buffer_num				[ get_parameter_value "buffer_num"]
	set fifo_use				[ get_parameter_value "fifo_use"]
	set video_width				[ get_parameter_value "video_width"]
	set video_height			[ get_parameter_value "video_height"]
	set video_interlaced		[ get_parameter_value "video_interlaced"]
	set runtime_control			[ get_parameter_value "runtime_control"]
	set control_mode			[ get_parameter_value "control_mode"]

	set data_width				[ expr ($data_bits * $data_planes) ]
	set fifo_use_width 			[ format "%.0f" [ expr ceil (log($fifo_depth) / (log (2))) ]]

	set data_width_p			"DATA_WIDTH:$data_width"
	set data_bits_p				"DATA_BITS:$data_bits"
	set data_planes_p			"DATA_PLANES:$data_planes"
	set fifo_use_width_p		"FIFO_USED_WIDTH:$fifo_use_width"
	set buffer_num_p			"FIFO_BUFFER_NUM:$buffer_num"
	set vip_width_p				"VIP_WIDTH:16'd$video_width"
	set vip_height_p			"VIP_HEIGHT:16'd$video_height"
	set vip_interlaced_p		"VIP_INTERLACED:4'b$video_interlaced"

	set datain_mod_fs_same_clk_if			"DATAIN_MOD_FS_SAME_CLOCK:0"
	set datain_mod_fs_not_same_clk_if		"DATAIN_MOD_FS_NOT_SAME_CLOCK:0"

	set datain_mod_part_st_same_clk_if		"DATAIN_MOD_PART_ST_SAME_CLOCK:0"
	set datain_mod_part_st_not_same_clk_if	"DATAIN_MOD_PART_ST_NOT_SAME_CLOCK:0"

	set datain_mod_raw_st_if				"DATAIN_MOD_RAW_ST:0"

	switch $data_mode {
		1 {
			if { $same_clk } {
				set datain_mod_fs_same_clk_if			"DATAIN_MOD_FS_SAME_CLOCK:1"
			} else {
				set datain_mod_fs_not_same_clk_if		"DATAIN_MOD_FS_NOT_SAME_CLOCK:1"
			}
		}
		2 {
			if { $same_clk } {
				set datain_mod_part_st_same_clk_if		"DATAIN_MOD_PART_ST_SAME_CLOCK:1"
			} else {
				set datain_mod_part_st_not_same_clk_if	"DATAIN_MOD_PART_ST_NOT_SAME_CLOCK:1"
			}
		}
		3 { set datain_mod_raw_st_if					"DATAIN_MOD_RAW_ST:1" }
	}

	if { $fifo_use } {
		set fifo_usedw_if				"FIFO_USEDW:1"
	} else {
		set fifo_usedw_if				"FIFO_USEDW:0"
	}

	if { $runtime_control } {
		if { $control_mode } {
			set runtime_control_if		"RUNTIME_CONTROL:0"
			set export_inf_if			"EXPORT_INF:1"
		} else {
			set runtime_control_if		"RUNTIME_CONTROL:1"
			set export_inf_if			"EXPORT_INF:0"			
		}
	} else {
		set runtime_control_if			"RUNTIME_CONTROL:0"
		set export_inf_if				"EXPORT_INF:0"	
	}

	set params "$data_width_p;$data_bits_p;$data_planes_p;$fifo_use_width_p;$buffer_num_p;$vip_width_p;$vip_height_p;$vip_interlaced_p"
	set sections "$datain_mod_fs_same_clk_if;$datain_mod_fs_not_same_clk_if;$datain_mod_part_st_same_clk_if;$datain_mod_part_st_not_same_clk_if;$datain_mod_raw_st_if;$runtime_control_if;$export_inf_if;$fifo_usedw_if"

	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]

	add_file "$dest_dir$dest_name.v" SYNTHESIS
	alt_up_generate "$dest_dir$dest_name.v" "hdl/raw_vip_bridge_top.v" "raw_vip_bridge_top" $dest_name $params $sections
}
# | 
# +-----------------------------------
