# TCL File Generated by Component Editor 13.1
# Mon Oct 17 16:07:01 CST 2016
# DO NOT MODIFY


# 
# blind_pixel "blind_pixel" v1.0
# Yogurt 2016.10.17.16:07:01
# 
# 

source "../../lib/aup_ip_generator.tcl"


# 
# module blind_pixel
# 
set_module_property DESCRIPTION "Blind Pixel Process"
set_module_property NAME blind_pixel
set_module_property VERSION 1.0
set_module_property GROUP my_ip/video
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME blind_pixel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate


# 
# file sets
# 
add_file "hdl/blind_pixel_decode.v" SYNTHESIS
add_file "hdl/blind_pixel_encode.v" SYNTHESIS
add_file "hdl/blind_pixel_proc.v" SYNTHESIS
add_file "hdl/blind_pixel_ram.v" SYNTHESIS

# 
# parameters
# 
add_parameter data_width positive 10
set_parameter_property data_width DISPLAY_NAME "Data Bits"
set_parameter_property data_width UNITS NONE
set_parameter_property data_width DISPLAY_UNITS "Bits"
set_parameter_property data_width ALLOWED_RANGES 4:32
set_parameter_property data_width AFFECTS_ELABORATION true
set_parameter_property data_width AFFECTS_GENERATION true
set_parameter_property data_width VISIBLE true
set_parameter_property data_width ENABLED true


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset rst_n reset_n Input 1


proc elaborate {} {
	set data_width				[get_parameter_value "data_width"]

	# 
	# connection point control
	# 
	add_interface control avalon end
	set_interface_property control addressUnits WORDS
	set_interface_property control associatedClock clock
	set_interface_property control associatedReset reset
	set_interface_property control bitsPerSymbol 8
	set_interface_property control burstOnBurstBoundariesOnly false
	set_interface_property control burstcountUnits WORDS
	set_interface_property control explicitAddressSpan 0
	set_interface_property control holdTime 0
	set_interface_property control linewrapBursts false
	set_interface_property control maximumPendingReadTransactions 0
	set_interface_property control readLatency 1
	set_interface_property control readWaitStates 0
	set_interface_property control readWaitTime 0
	set_interface_property control setupTime 0
	set_interface_property control timingUnits Cycles
	set_interface_property control writeWaitTime 0
	set_interface_property control ENABLED true

	add_interface_port control av_address address Input 2
	add_interface_port control av_write write Input 1
	add_interface_port control av_writedata writedata Input 32
	set_interface_assignment control embeddedsw.configuration.isFlash 0
	set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
	set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
	set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0

	# 
	# connection point ram
	# 
	add_interface ram avalon end
	set_interface_property ram addressUnits WORDS
	set_interface_property ram associatedClock clock
	set_interface_property ram associatedReset reset
	set_interface_property ram bitsPerSymbol 8
	set_interface_property ram burstOnBurstBoundariesOnly false
	set_interface_property ram burstcountUnits WORDS
	set_interface_property ram explicitAddressSpan 0
	set_interface_property ram holdTime 0
	set_interface_property ram linewrapBursts false
	set_interface_property ram maximumPendingReadTransactions 0
	set_interface_property ram readLatency 1
	set_interface_property ram readWaitStates 0
	set_interface_property ram readWaitTime 0
	set_interface_property ram setupTime 0
	set_interface_property ram timingUnits Cycles
	set_interface_property ram writeWaitTime 0
	set_interface_property ram ENABLED true

	add_interface_port ram ram_write write Input 1
	add_interface_port ram ram_writedata writedata Input 32
	add_interface_port ram ram_read read Input 1
	add_interface_port ram ram_readdata readdata Output 32
	add_interface_port ram ram_byteenable byteenable Input 4
	add_interface_port ram ram_address address Input 8
	set_interface_assignment ram embeddedsw.configuration.isFlash 0
	set_interface_assignment ram embeddedsw.configuration.isMemoryDevice 0
	set_interface_assignment ram embeddedsw.configuration.isNonVolatileStorage 0
	set_interface_assignment ram embeddedsw.configuration.isPrintableDevice 0

	# 
	# connection point din
	# 
	add_interface din avalon_streaming end
	set_interface_property din associatedClock clock
	set_interface_property din associatedReset reset
	set_interface_property din dataBitsPerSymbol $data_width
	set_interface_property din errorDescriptor ""
	set_interface_property din firstSymbolInHighOrderBits true
	set_interface_property din maxChannel 0
	set_interface_property din readyLatency 1
	set_interface_property din ENABLED true

	add_interface_port din din_data data Input $data_width
	add_interface_port din din_ready ready Output 1
	add_interface_port din din_valid valid Input 1
	add_interface_port din din_startofpacket startofpacket Input 1
	add_interface_port din din_endofpacket endofpacket Input 1

	# 
	# connection point dout
	# 
	add_interface dout avalon_streaming start
	set_interface_property dout associatedClock clock
	set_interface_property dout associatedReset reset
	set_interface_property dout dataBitsPerSymbol $data_width
	set_interface_property dout errorDescriptor ""
	set_interface_property dout firstSymbolInHighOrderBits true
	set_interface_property dout maxChannel 0
	set_interface_property dout readyLatency 1
	set_interface_property dout ENABLED true

	add_interface_port dout dout_data data Output $data_width
	add_interface_port dout dout_ready ready Input 1
	add_interface_port dout dout_valid valid Output 1
	add_interface_port dout dout_startofpacket startofpacket Output 1
	add_interface_port dout dout_endofpacket endofpacket Output 1
}

proc generate {} {
	set data_width				[get_parameter_value "data_width"]

	set data_width_p			"DATA_WIDTH:$data_width"

	set params "$data_width_p"
	set sections ""

	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]

	add_file "$dest_dir$dest_name.v" SYNTHESIS
	alt_up_generate "$dest_dir$dest_name.v" "hdl/blind_pixel_top.v" "blind_pixel_top" $dest_name $params $sections
}
