# TCL File Generated by Component Editor 12.1sp1
# Tue Mar 29 14:10:37 CST 2016
# DO NOT MODIFY


# 
# avalon_slave_to_wb_master "Avalon Slave to WishBone Master" v1.0
# Yogurt 2016.03.29.14:10:37
# Convert Avalon Slave Interface to WishBone Master Interface
# 

source "../../lib/aup_ip_generator.tcl"

# 
# module avalon_slave_to_wb_master
# 
set_module_property DESCRIPTION "Convert Avalon Slave Interface to WishBone Master Interface"
set_module_property NAME avalon_slave_to_wb_master
set_module_property VERSION 1.0
set_module_property GROUP my_ip/interface
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME "Avalon Slave to WishBone Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME "Address Bus Width"
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH AFFECTS_ELABORATION true
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION true
set_parameter_property ADDR_WIDTH VISIBLE true
set_parameter_property ADDR_WIDTH ENABLED true

add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DISPLAY_NAME "Data Bus Width"
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32}
set_parameter_property DATA_WIDTH AFFECTS_ELABORATION true
set_parameter_property DATA_WIDTH AFFECTS_GENERATION true
set_parameter_property DATA_WIDTH VISIBLE true
set_parameter_property DATA_WIDTH ENABLED true


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset rst_n reset_n Input 1


proc elaborate {} {
	set addr_width [ get_parameter_value "ADDR_WIDTH" ]
	set data_width [ get_parameter_value "DATA_WIDTH" ]
	set data_bytes [ expr ($data_width/8)]

	# 
	# connection point avalon_slave
	# 
	add_interface avalon_slave avalon end
	set_interface_property avalon_slave addressUnits WORDS
	set_interface_property avalon_slave associatedClock clock
	set_interface_property avalon_slave associatedReset reset
	set_interface_property avalon_slave bitsPerSymbol 8
	set_interface_property avalon_slave burstOnBurstBoundariesOnly false
	set_interface_property avalon_slave burstcountUnits WORDS
	set_interface_property avalon_slave explicitAddressSpan 0
	set_interface_property avalon_slave holdTime 0
	set_interface_property avalon_slave linewrapBursts false
	set_interface_property avalon_slave maximumPendingReadTransactions 1
	set_interface_property avalon_slave readLatency 0
	set_interface_property avalon_slave readWaitTime 0
	set_interface_property avalon_slave setupTime 0
	set_interface_property avalon_slave timingUnits Cycles
	set_interface_property avalon_slave writeWaitTime 0
	set_interface_property avalon_slave ENABLED true

	add_interface_port avalon_slave av_chipselect chipselect Input 1
	add_interface_port avalon_slave av_byteenable byteenable Input $data_bytes
	add_interface_port avalon_slave av_address address Input $addr_width
	add_interface_port avalon_slave av_read read Input 1
	add_interface_port avalon_slave av_write write Input 1
	add_interface_port avalon_slave av_readdata readdata Output $data_width
	add_interface_port avalon_slave av_readdatavalid readdatavalid Output 1
	add_interface_port avalon_slave av_writedata writedata Input $data_width
	add_interface_port avalon_slave av_waitrequest waitrequest Output 1
	set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
	set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
	set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
	set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


	# 
	# connection point wishbone_master
	# 
	add_interface wishbone_master conduit end
	set_interface_property wishbone_master associatedClock clock
	set_interface_property wishbone_master associatedReset reset
	set_interface_property wishbone_master ENABLED true

	add_interface_port wishbone_master wb_cyc_o export Output 1
	add_interface_port wishbone_master wb_stb_o export Output 1
	add_interface_port wishbone_master wb_we_o export Output 1
	add_interface_port wishbone_master wb_adr_o export Output $addr_width
	add_interface_port wishbone_master wb_dat_o export Output $data_width
	add_interface_port wishbone_master wb_dat_i export Input $data_width
	add_interface_port wishbone_master wb_sel_o export Output $data_bytes
	add_interface_port wishbone_master wb_ack_i export Input 1
}

proc generate {} {
	set addr_width [ get_parameter_value "ADDR_WIDTH" ]
	set data_width [ get_parameter_value "DATA_WIDTH" ]
	set data_bytes [ expr ($data_width/8)]

	set params "ADDR_WIDTH:$addr_width;DATA_WIDTH:$data_width;DATA_BYTES:$data_bytes"
	set sections ""


	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]
	
	add_file "$dest_dir$dest_name.v" {SYNTHESIS SIMULATION}
	alt_up_generate "$dest_dir$dest_name.v" "hdl/avalon_slave_to_wb_master.v" "avalon_slave_to_wb_master" $dest_name $params $sections
}
