# TCL File Generated by Component Editor 13.1
# Mon May 23 16:23:59 CST 2016
# DO NOT MODIFY


# 
# detector_module "detector_module" v1.0
#  2016.05.23.16:23:59
# 
# 

source "../../lib/aup_ip_generator.tcl"

# 
# module detector_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME detector_module
set_module_property VERSION 1.1
set_module_property GROUP my_ip/video
set_module_property AUTHOR "Yogurt"
set_module_property DISPLAY_NAME detector_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate


# 
# parameters
# 
add_parameter clk_fre positive 13000000
set_parameter_property clk_fre DISPLAY_NAME "Video Clock Frequency"
set_parameter_property clk_fre UNITS NONE
set_parameter_property clk_fre DISPLAY_UNITS "Hz"
set_parameter_property clk_fre AFFECTS_ELABORATION false
set_parameter_property clk_fre AFFECTS_GENERATION true
set_parameter_property clk_fre VISIBLE true
set_parameter_property clk_fre ENABLED true

add_parameter data_width positive 10
set_parameter_property data_width DISPLAY_NAME "Data Bits"
set_parameter_property data_width UNITS NONE
set_parameter_property data_width DISPLAY_UNITS "Bits"
set_parameter_property data_width ALLOWED_RANGES 4:32
set_parameter_property data_width AFFECTS_ELABORATION true
set_parameter_property data_width AFFECTS_GENERATION true
set_parameter_property data_width VISIBLE true
set_parameter_property data_width ENABLED true


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset rst_n reset_n Input 1


proc elaborate {} {
	set data_width				[get_parameter_value "data_width"]

	set clk_fre [ get_interface_property clock clockRate ]
	if { $clk_fre <= 0 } {
		set_parameter_property clk_fre ENABLED true
	} else {
		set_parameter_property clk_fre ENABLED false
		set_parameter_value "clk_fre" $clk_fre
	}

	# 
	# connection point dout
	# 
	add_interface dout avalon_streaming start
	set_interface_property dout associatedClock clock
	set_interface_property dout associatedReset reset
	set_interface_property dout dataBitsPerSymbol $data_width
	set_interface_property dout errorDescriptor ""
	set_interface_property dout firstSymbolInHighOrderBits true
	set_interface_property dout maxChannel 0
	set_interface_property dout readyLatency 1
	set_interface_property dout ENABLED true

	add_interface_port dout dout_data data Output $data_width
	add_interface_port dout dout_valid valid Output 1
	add_interface_port dout dout_startofpacket startofpacket Output 1
	add_interface_port dout dout_endofpacket endofpacket Output 1


	# 
	# connection point avalon_control
	# 
	add_interface avalon_control avalon end
	set_interface_property avalon_control addressUnits WORDS
	set_interface_property avalon_control associatedClock clock
	set_interface_property avalon_control associatedReset reset
	set_interface_property avalon_control bitsPerSymbol 8
	set_interface_property avalon_control burstOnBurstBoundariesOnly false
	set_interface_property avalon_control burstcountUnits WORDS
	set_interface_property avalon_control explicitAddressSpan 0
	set_interface_property avalon_control holdTime 0
	set_interface_property avalon_control linewrapBursts false
	set_interface_property avalon_control maximumPendingReadTransactions 0
	set_interface_property avalon_control readLatency 1
	set_interface_property avalon_control readWaitStates 0
	set_interface_property avalon_control readWaitTime 0
	set_interface_property avalon_control setupTime 0
	set_interface_property avalon_control timingUnits Cycles
	set_interface_property avalon_control writeWaitTime 0
	set_interface_property avalon_control ENABLED true

	add_interface_port avalon_control av_address address Input 1
	add_interface_port avalon_control av_write write Input 1
	add_interface_port avalon_control av_writedata writedata Input 32
}


proc generate {} {
	set clk_fre					[get_parameter_value "clk_fre"]
	set data_width				[get_parameter_value "data_width"]
	set frame_cnt				[ format "%.0f" [ expr round ($clk_fre/50-234386) ]]

	set frame_cnt_p				"FRAME_CNT:$frame_cnt"
	set data_width_p			"DATA_WIDTH:$data_width"

	set params "$frame_cnt_p;$data_width_p"
	set sections ""

	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]

	add_file "$dest_dir$dest_name.v" SYNTHESIS
	alt_up_generate "$dest_dir$dest_name.v" "hdl/detector_driver.v" "detector_driver" $dest_name $params $sections
}
