# TCL File Generated by Component Editor 13.1
# Thu Jul 21 17:55:32 CST 2016
# DO NOT MODIFY


# 
# image_store "image_store" v1.0
# Yogurt 2016.07.21.17:55:32
# 
# 


source "../../lib/aup_ip_generator.tcl"

# 
# module image_store
# 
set_module_property DESCRIPTION "Store Avalon-ST Format Image"
set_module_property NAME image_store
set_module_property VERSION 1.0
set_module_property GROUP my_ip/video
set_module_property AUTHOR Yogurt
set_module_property DISPLAY_NAME image_store
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate


# 
# file sets
# 
add_file "hdl/image_store_avalon_master.v" SYNTHESIS
add_file "hdl/image_store_avalon_slave.v" SYNTHESIS
add_file "hdl/image_store_decode.v" SYNTHESIS
add_file "hdl/image_store_splite.v" SYNTHESIS


# 
# parameters
# 
add_parameter dout_width INTEGER 10
set_parameter_property dout_width DISPLAY_NAME "Video Width"
set_parameter_property dout_width UNITS None
set_parameter_property dout_width DISPLAY_UNITS bits
set_parameter_property dout_width AFFECTS_ELABORATION true
set_parameter_property dout_width AFFECTS_GENERATION true
set_parameter_property dout_width ALLOWED_RANGES 4:32
set_parameter_property dout_width VISIBLE true
set_parameter_property dout_width ENABLED true

add_parameter data_width INTEGER 8
set_parameter_property data_width DISPLAY_NAME "Master Port Width"
set_parameter_property data_width UNITS None
set_parameter_property data_width DISPLAY_UNITS bits
set_parameter_property data_width AFFECTS_ELABORATION true
set_parameter_property data_width AFFECTS_GENERATION true
set_parameter_property data_width ALLOWED_RANGES {8 16 32 64}
set_parameter_property data_width VISIBLE true
set_parameter_property data_width ENABLED true

add_parameter store_width INTEGER 8
set_parameter_property store_width DISPLAY_NAME "Maximum Store Image Once"
set_parameter_property store_width UNITS None
set_parameter_property store_width DISPLAY_UNITS frames
set_parameter_property store_width AFFECTS_ELABORATION false
set_parameter_property store_width AFFECTS_GENERATION true
set_parameter_property store_width ALLOWED_RANGES {2 4 8 16 32}
set_parameter_property store_width VISIBLE true
set_parameter_property store_width ENABLED true

# +-----------------------------------
# | Elaboration function
# | 
proc elaborate {} {
	set data_width				[ get_parameter_value "data_width"]
	set dout_width				[ get_parameter_value "dout_width"]

	# 
	# connection point clock
	# 
	add_interface clock clock end
	set_interface_property clock ENABLED true

	add_interface_port clock clk clk Input 1

	# 
	# connection point reset
	# 
	add_interface reset reset end
	set_interface_property reset associatedClock clock
	set_interface_property reset synchronousEdges DEASSERT
	set_interface_property reset ENABLED true

	add_interface_port reset rst_n reset_n Input 1

	# 
	# connection point din
	# 
	add_interface din avalon_streaming end
	set_interface_property din associatedClock clock
	set_interface_property din associatedReset reset
	set_interface_property din dataBitsPerSymbol $dout_width
	set_interface_property din errorDescriptor ""
	set_interface_property din firstSymbolInHighOrderBits true
	set_interface_property din maxChannel 0
	set_interface_property din readyLatency 1
	set_interface_property din ENABLED true

	add_interface_port din din_data data Input $dout_width
	add_interface_port din din_ready ready Output 1
	add_interface_port din din_valid valid Input 1
	add_interface_port din din_startofpacket startofpacket Input 1
	add_interface_port din din_endofpacket endofpacket Input 1


	# 
	# connection point dout
	# 
	add_interface dout avalon_streaming start
	set_interface_property dout associatedClock clock
	set_interface_property dout associatedReset reset
	set_interface_property dout dataBitsPerSymbol $dout_width
	set_interface_property dout errorDescriptor ""
	set_interface_property dout firstSymbolInHighOrderBits true
	set_interface_property dout maxChannel 0
	set_interface_property dout readyLatency 1
	set_interface_property dout ENABLED true

	add_interface_port dout dout_data data Output $dout_width
	add_interface_port dout dout_valid valid Output 1
	add_interface_port dout dout_ready ready Input 1
	add_interface_port dout dout_startofpacket startofpacket Output 1
	add_interface_port dout dout_endofpacket endofpacket Output 1

	# 
	# connection point control
	# 
	add_interface control avalon end
	set_interface_property control addressUnits WORDS
	set_interface_property control associatedClock clock
	set_interface_property control associatedReset reset
	set_interface_property control bitsPerSymbol 8
	set_interface_property control burstOnBurstBoundariesOnly false
	set_interface_property control burstcountUnits WORDS
	set_interface_property control explicitAddressSpan 0
	set_interface_property control holdTime 0
	set_interface_property control linewrapBursts false
	set_interface_property control maximumPendingReadTransactions 0
	set_interface_property control readLatency 1
	set_interface_property control readWaitTime 0
	set_interface_property control setupTime 0
	set_interface_property control timingUnits Cycles
	set_interface_property control writeWaitTime 0
	set_interface_property control ENABLED true

	add_interface_port control avs_address address Input 2
	add_interface_port control avs_read read Input 1
	add_interface_port control avs_readdata readdata Output 32
	add_interface_port control avs_write write Input 1
	add_interface_port control avs_writedata writedata Input 32
	set_interface_assignment control embeddedsw.configuration.isFlash 0
	set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
	set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
	set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0


	# 
	# connection point master
	# 
	add_interface master avalon start
	set_interface_property master addressUnits SYMBOLS
	set_interface_property master associatedClock clock
	set_interface_property master associatedReset reset
	set_interface_property master bitsPerSymbol 8
	set_interface_property master burstOnBurstBoundariesOnly false
	set_interface_property master burstcountUnits WORDS
	set_interface_property master doStreamReads false
	set_interface_property master doStreamWrites false
	set_interface_property master holdTime 0
	set_interface_property master linewrapBursts false
	set_interface_property master maximumPendingReadTransactions 0
	set_interface_property master readLatency 0
	set_interface_property master readWaitTime 0
	set_interface_property master setupTime 0
	set_interface_property master timingUnits Cycles
	set_interface_property master writeWaitTime 0
	set_interface_property master ENABLED true

	add_interface_port master avm_address address Output 32
	add_interface_port master avm_write write Output 1
	add_interface_port master avm_writedata writedata Output $data_width
	add_interface_port master avm_waitrequest waitrequest Input 1
}
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	set data_width				[ get_parameter_value "data_width"]
	set dout_width				[ get_parameter_value "dout_width"]
	set store_width				[ get_parameter_value "store_width"]
	set data_log 				[ format "%.0f" [ expr ceil (log($data_width) / (log (2))) ]]
	set store_log				[ format "%.0f" [ expr ceil (log($store_width) / (log (2))) ]]

	set data_log_p				"AVM_WIDTH_LOG:$data_log"
	set dout_width_p			"DATA_WIDTH:$dout_width"
	set store_log_p				"STORE_WIDTH:$store_log"

	set params 					"$data_log_p;$dout_width_p;$store_log_p"
	set sections				""

	set dest_dir 				[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name				[ get_generation_property OUTPUT_NAME ]

	add_file "$dest_dir$dest_name.v" SYNTHESIS
	alt_up_generate "$dest_dir$dest_name.v" "hdl/image_store_top.v" "image_store_top" $dest_name $params $sections
}
# | 
# +-----------------------------------




